// Generated by Haxe 3.4.7
(function () { "use strict";
var MyValue = function(value) {
	this.value = value;
};
var Main = function() { };
Main.main = function() {
	var a = new MyValue_$String("Hello");
	var b = new MyValue_$Int(42);
};
var MyValue_$Int = function(value) {
	this.value = value;
};
var MyValue_$String = function(value) {
	this.value = value;
};
Main.main();
})();
