// Generated by Haxe 3.4.7
(function () { "use strict";
var MyValue = function(value) {
	this.value = value;
};
var Main = function() { };
Main.main = function() {
	var a = new MyValue("Hello");
	var b = new MyValue(42);
};
Main.main();
})();
