// Generated by Haxe 3.4.7
(function () { "use strict";
var Point3D = function(x,y,z) {
	this.x = x;
	this.y = y;
	this.z = z;
};
var Main = function() { };
Main.main = function() {
	var p_z;
	var p_y;
	var p_x = 0.0;
	p_y = 1;
	p_z = 2;
};
Main.main();
})();
