// Generated by Haxe 3.4.7
(function () { "use strict";
var Main = function() {
	this.set_add2(10);
	this.add3 = this.add2 * 2;
};
Main.main = function() {
	console.log("bar2");
	Main.member = "foo";
	console.log(Main.member);
	var m = new Main();
	console.log(m.add2);
	console.log(m.get_add3());
	m.set_add2_2(m.set_add2_2(m.add3 = m.add2));
	console.log(m.get_add2_2());
	console.log(m.get_add3());
};
Main.prototype = {
	set_add2: function(x) {
		return this.add2 = x + 2;
	}
	,get_add3: function() {
		return this.add3 + 3;
	}
	,get_add2_2: function() {
		return this.add2_2 + 2;
	}
	,set_add2_2: function(x) {
		return this.add2_2 = x + 2;
	}
};
Main.member = "bar";
Main.memberConst = "bar2";
Main.main();
})();
